### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by astewa25** [a-kihiko/Music-is-Playing#1]
I was able to get a website up previously, then I deleted the pages in the repositories.  When I put in the new files, it ran again, then I deleted those and now my website does not pull up. I have cleared my browser history and cache and it is still not working. I am not sure what to do.

**Comment by astewa25** [comment]
Here is the website

https://a-kihiko.github.io/Music-is-Playing/#

**Comment by a-kihiko** [comment]
I think there are some missing elements, but I have not see the full code yet. Please send to me what you have on your end.
